themes/17f70712-4530-42d0-ba0f-fa25bcbf2ddc/colors.json
Fixing the tertiary color that does not match the official color in the Vesper color scheme.
Here is the screenshot of the hex code of the color in the Vesper color scheme source code.
=> Update theme: Vesper Dark

themes/58649066-2b6f-4a5b-af6d-c3d21d16fc00/chrome.css, themes/58649066-2b6f-4a5b-af6d-c3d21d16fc00/preferences.json, themes/58649066-2b6f-4a5b-af6d-c3d21d16fc00/readme.md, themes/58649066-2b6f-4a5b-af6d-c3d21d16fc00/theme.json
This fix adds a more pleasant gradient for light mode users, and prevents the URL bar from overlapping the private mode icon should the browser width be too small or the URL bar be otherwise expanded.
Fixes danm36/zen-browser-private-browsing-toolbar-highlighting#1
=> Update theme: Private Mode Highlighting

themes/6a5e8204-ea7f-4c3d-a6fc-de503b470d70/chrome.css
This reduces the scope of styles so that they apply only on Newtab page and Homepage. Homepage scope is needed when you have set Newtab as your homepage. If this is not done, the homepage will appear using unstyled newtab page when you open the browser.
=> Apply only on about:newtab and about:home

themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/chrome.css, themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/preferences.json, themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/readme.md, themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/theme.json
- Added option to have more box like corners (less rounded corners)
- Decreased general width of pins by a little bit (so that they don't stretch too hard)
- Removed some unnecessary code
- Make the gap underneath pinned tabs align with compact option
- Increased version to 1.3.1
=> Update Theme: SuperPins

themes/d93e67f8-e5e1-401e-9b82-f9d5bab231e6/chrome.css, themes/d93e67f8-e5e1-401e-9b82-f9d5bab231e6/readme.md, themes/d93e67f8-e5e1-401e-9b82-f9d5bab231e6/theme.json
Quick Fixes after Zens latest update:
- Make border radius option to create circle like corners (like in og zen) 
- Fixed blur not working (scuffed af solution, uses clip path like in og zen (was the only way i found how to fix it for now) I really need to find a better solution)
- Increased version to 1.1.1
=> Update Theme: Super Url Bar

themes/053a3ffa-9233-4554-88f3-076e6a6ebb43/chrome.css, themes/053a3ffa-9233-4554-88f3-076e6a6ebb43/theme.json
New browser versions hides the favicon on hover to show the mute button. As there is no mute button to show, this forces the favicon to always be visible.
Note: `.tab-icon-image` is quite an unspecific selector, but I don't believe that should cause any visual issues with other parts of the UI, as opacity is rarely used. Let me know if this is an issue and I can narrow it down!
=> Update Theme: Hide tab mute

themes/af7ee14f-e9d4-4806-8438-c59b02b77715/chrome.css, themes/af7ee14f-e9d4-4806-8438-c59b02b77715/preferences.json, themes/af7ee14f-e9d4-4806-8438-c59b02b77715/readme.md, themes/af7ee14f-e9d4-4806-8438-c59b02b77715/theme.json
- Make gradient work on bookmark toolbar
- Added support for the following mods:
"Floating Compact Sidebar" and "Floating Toolbar" (Fixes https://github.com/JLBlk/Zen-Themes/issues/22)
- Added new Gradient Preset: "Zen Galaxy/Dream Legacy Theme"
- Increased Version to 1.2.0
=> Update Theme: SuperGradient

themes/6cd4bca9-f17d-4461-b554-844d69a4887c/chrome.css, themes/6cd4bca9-f17d-4461-b554-844d69a4887c/preferences.json, themes/6cd4bca9-f17d-4461-b554-844d69a4887c/theme.json
1. Allows the buttons to follow whatever themes the user is using. (Button's bg color is set to browser's border color)
2. Allows for a more identical MacOS exit menu.
=> Update theme: Zen minimal exit menu 1.0.1

.github/workflows/update-theme-date.yml, scripts/rebuild_themes.py, scripts/update_theme_date.py, themes/253a3a74-0cc4-47b7-8b82-996a64f030d5/theme.json, themes/4596d8f9-f0b7-4aeb-aa92-851222dc1888/theme.json, themes/4ab93b88-151c-451b-a1b7-a1e0e28fa7f8/theme.json, themes/5c4d7772-d963-4672-ab03-e9d541438881/theme.json, themes/5ca67725-1f43-4ff2-9fcf-0c59af71c73a/theme.json, themes/664c54f9-d97d-410b-a479-23dd8a08a628/theme.json, themes/753c7518-237d-480a-abfd-1f42a7eabacc/theme.json, themes/7ba20fe1-7286-4b1f-9bf6-39d40bec8ae0/theme.json, themes/bb61b145-6875-4afe-86f2-ab00024459dc/theme.json, themes/f7c71d9a-bce2-420f-ae44-a64bd92975ab/theme.json
- Fixed an issue where tags could be added multiple times when rebuilding themes.
- Fixed an issue where `createdAt` property was not being added for pull requests created prior to introduction of new properties.
- Fixed an issue where `tags` property was not being added for pull requests created prior to introduction of new properties.
- Updated the affected `theme.json` files for themes merged today.
- Fixed an issue where the action fails if another commit is made before action finishes
- Made the action only initiate when changes are detected in the `themes/` subdirectory
After merging, please manually run the `Submit PR` action so that `themes.json` can be rebuilt
=> Fix Theme Metadata Duplication and Add Missing Properties for Recent Pull Requests

themes/46690a54-5eff-4141-8af8-9cd772ab6e2c/chrome.css
I originally made an issue for is (#520), following the instructions of [this page](https://docs.zen-browser.app/themes-store/themes-marketplace-submission-guidelines). Now I'm making this PR at the request of @KiKaraage.
**Quick recap:**
The change is quite simple, it's about the hover zone for the sidebar when hidden. It's too large and sometimes interferes with the UI elements of webpages, making them unreachable.
I also fixed a minor inconsistency in top separation not being equal to the bottom one.
**Later, after a zen update changed the sidebar, I also made this update:**
The new sidebar/toolbox added a padding and border on the `#titlebar` element, which really doesn't work with the floating style. So I've also removed this.
=> fix(float-compact-sidebar): Fix hover zone when collapsed.

themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/chrome.css, themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/theme.json
Adds small rectangles to improve visibility on lighter background. There is a small overlap with top border which I wasn't able to fix without reducing top margin which caused [spacing issue](https://github.com/n7itro/Zen-Themes/issues/19). Fix was adapted from Firefox Mod Blur transparent bookmark bar mod.
=> Bookmarks toolbar visibility fix

themes/00aeb359-cce5-4eb5-8c5c-5f928a715664/chrome.css, themes/00aeb359-cce5-4eb5-8c5c-5f928a715664/preferences.json, themes/00aeb359-cce5-4eb5-8c5c-5f928a715664/theme.json
fixed the cat position when resizing of window and will only be visible in compact mode
=> Update theme : Nyan Catto Mod

themes/bfcc400a-4ecb-4752-bfd2-a68f116a2722/chrome.css, themes/bfcc400a-4ecb-4752-bfd2-a68f116a2722/preferences.json, themes/bfcc400a-4ecb-4752-bfd2-a68f116a2722/readme.md, themes/bfcc400a-4ecb-4752-bfd2-a68f116a2722/theme.json
Adds 2 new options for each view mode (normal and split)
+ Hide top bar
> Removes the gap caused by the top bar in single toolbar mode.
+ Remove top bar
> Stops the top bar from ever rendering.
Fixes splitters in split view when gaps are disabled (the things used to resize tabs). Vertical ones were off-center and horizontal ones had a height of 0 so you couldn't even interact with them.
Updates readme to improve clarity
=> Update theme: No Gaps

themes/bd92a9a0-1c00-4187-a66e-94c389fa5a59/chrome.css, themes/bd92a9a0-1c00-4187-a66e-94c389fa5a59/preferences.json, themes/bd92a9a0-1c00-4187-a66e-94c389fa5a59/readme.md, themes/bd92a9a0-1c00-4187-a66e-94c389fa5a59/theme.json
- Add support for sidebar on the right (including option to keep tab icons on the right as well)
- Add support for flexible space in top/bottom buttons
- Add support for addon action buttons
- Fix top buttons occupying space when empty
- Fix sidebar collapsing when dragging a tab
- Fix sidebar collapsing when contextmenu is open
- Fix compact mode design
=> Update Sidebar Expand on Hover to 1.1.1

themes/4ab93b88-151c-451b-a1b7-a1e0e28fa7f8/chrome.css, themes/4ab93b88-151c-451b-a1b7-a1e0e28fa7f8/preferences.json, themes/4ab93b88-151c-451b-a1b7-a1e0e28fa7f8/theme.json
Updated to work on Zen 1.7.3b tab bar changes (and 1.7.2t) with the option for 1.7.2b or older.
=> Update Theme: No Sidebar Scrollbar

themes/39907934-59e9-4e42-89f0-a254d3c5e280/preferences.json
This will prevent installing the theme from automatically and persistently enabling a transparent viewport, causing issues with background colour on many websites. This is a very important change due to the frequency of inexperienced users running into this problem.
=> Disable browser.tabs.allow_transparent_browser by default

themes/6cd4bca9-f17d-4461-b554-844d69a4887c/chrome.css, themes/6cd4bca9-f17d-4461-b554-844d69a4887c/preferences.json, themes/6cd4bca9-f17d-4461-b554-844d69a4887c/theme.json
Re-pull request because the old one seems to be abandoned. This update allows the user to have the buttons colorful by default.
=> Update theme: Zen Minimal Exit Menu

themes/a5f6a231-e3c8-4ce8-8a8e-3e93efd6adec/theme.json
preferences isn't added on theme.json. This commit adds it to the themes.json file.
also: gotta add more notes on documentation; When a mod is submitted without preferences, and if in the future it will have one, theme.json needs to be updated with the "preferences" key.
=> Update theme: Cleaned URL bar

themes/5c4d7772-d963-4672-ab03-e9d541438881/chrome.css
Adjusted sound icon size/position; changed toggling in compact:
- Increased size and margin, and vertically centered new Zen sound playing icon in the tab.
- When in compact mode or with sidebar collapsed: Removed pointer events for sound playing button if tab is not the currently selected tab. Prevents unintentional toggling of the sound button when selecting or moving a tab with sound playing.
=> Update theme: Bigger Mute Button

themes/4c2bec61-7f6c-4e5c-bdc6-c9ad1aba1827/readme.md, themes/4c2bec61-7f6c-4e5c-bdc6-c9ad1aba1827/theme.json
Rename "Vertical Tab Groups" to "Vertical Split Tab Groups" and update description to clear up confusion about the experimental "Tab Groups" feature
=> Update Theme: Vertical Tab Groups

themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/chrome.css, themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/preferences.json, themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/readme.md, themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/theme.json
- bumped version to 1.5.0
Thanks to [@CosmoCreeper](https://github.com/CosmoCreeper):
- Fixes bleeding
- Fixes Tab seperator
- Adds growth for Pins & Essentials option
- Adds bottom option
- Adds dimming unloaded tabs options 
Thanks to [@gabry-ts](https://github.com/gabry-ts):
- Adds size options for:
- workspace indicator icon
- workspace icon
- tabs favicons
- pinned tabs
=> Update Mod: SuperPins

themes/22c9ec3b-7c62-46ae-991f-c8fff5046829/chrome.css, themes/22c9ec3b-7c62-46ae-991f-c8fff5046829/readme.md, themes/22c9ec3b-7c62-46ae-991f-c8fff5046829/theme.json
Additions (v1.0.5 - current version):
- Fixed incorrect numbering of pinned tabs, removed glance tabs from the tab count. (by CosmoCreeper)
=> Update theme: Tab Numbers v1.0.5

themes/a6335949-4465-4b71-926c-4a52d34bc9c0/chrome.css, themes/a6335949-4465-4b71-926c-4a52d34bc9c0/preferences.json, themes/a6335949-4465-4b71-926c-4a52d34bc9c0/readme.md, themes/a6335949-4465-4b71-926c-4a52d34bc9c0/theme.json
Changelog:
- Updated to 1.3.0
- Added options to change the find bar width and hide checkboxes (thanks to @Nepaletka!).
- Added options to hide the Find Status label and the Found Matches label.
- Defaulting Transparent Background to true.
- Renamed horizontal and vertical position placeholders to "Use default".
- Added more tags in the theme.json file.
- Changed mod description.
- Honestly, I like how clean the find bar looks with all options hidden :+1:
=> Update Theme: Better Find Bar

themes/22c9ec3b-7c62-46ae-991f-c8fff5046829/chrome.css, themes/22c9ec3b-7c62-46ae-991f-c8fff5046829/readme.md, themes/22c9ec3b-7c62-46ae-991f-c8fff5046829/theme.json
Reverted back to previous version, because it broke in version v1.12.6b of Zen Browser.
=> Update Theme: Tab Numbers (v1.0.7)

themes/e74cb40a-f3b8-445a-9826-1b1b6e41b846/chrome.css, themes/e74cb40a-f3b8-445a-9826-1b1b6e41b846/readme.md, themes/e74cb40a-f3b8-445a-9826-1b1b6e41b846/theme.json
1.0.1 Fix the issue where the window control buttons appear abnormal in Firefox 141.(Bugzilla 1789579)
=> Update: Custom uiFont

themes/a6335949-4465-4b71-926c-4a52d34bc9c0/chrome.css, themes/a6335949-4465-4b71-926c-4a52d34bc9c0/theme.json
Changelog:
- Updated to v1.3.4
- Added "search-bar" tag
- Replaced `--zen-colors-primary` with `--zen-primary-color` to fix a compatibility issue after Zen 1.5
- Replaced `--zen-colors-border` with `--input-border-color` just to make the find bar look better
=> Update theme: better-findbar
