themes.json
themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/chrome.css
themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/preferences.json
themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/readme.md

Adds expand-on-hover and expand-on-search feature.

Bookmark Toolbar Tweaks theme update

---

themes/782c1dae-bada-4f90-b00f-446e5f6e8402/chrome.css

hotfix compact sidebar theme

---

themes/64cdc40f-2366-4b5b-8bad-d0524682595e/chrome.css

Added support for toolbar theming in compact mode

Update Theme: Allow Toolbar Theming

---

themes/ecda11ae-d3fd-4052-8881-303b2504e3ce/colors.json

- Updated tertiary and border colors for better contrast.
- Added dialog background color.

Update Theme: Gruvbox

---

themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/chrome.css

Fixed bug that pevents bookmark toolbar from showing without expand features enabled

fixed bookmarks theme bug

---

themes/17f70712-4530-42d0-ba0f-fa25bcbf2ddc/chrome.css
themes/17f70712-4530-42d0-ba0f-fa25bcbf2ddc/theme.json

Adjusted the URL bar color to aesthetically match the background color.
Before:
After:

Update Theme: Vesper Dark

---

themes/49dbaa98-06ee-42bd-9a8e-834babef7a41/chrome.css

Adds hover effect and a fallback background color.
Closes #344

Update Collapsed Tab X Button theme

---

themes/35f24f2c-b211-43e2-9fe4-2c3bc217d9f7/chrome.css

Fixes an issue with the "Playing" indicator
Also formatted and added some comments

Update theme: Compact tabs title

---

themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/chrome.css
themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/theme.json

Fixes small issue with touch & normal interface density

Update Theme: Bookmark Toolbar Tweaks

---

themes/d93e67f8-e5e1-401e-9b82-f9d5bab231e6/chrome.css
themes/d93e67f8-e5e1-401e-9b82-f9d5bab231e6/preferences.json
themes/d93e67f8-e5e1-401e-9b82-f9d5bab231e6/readme.md
themes/d93e67f8-e5e1-401e-9b82-f9d5bab231e6/theme.json

- Renamed to Super Url Bar (also in json and all)
- Added option to blur background when url bar is in focus
- Added option to remove the border of the url bar
- Increased version to 1.1.0

Update Theme: Uniform Url Bar

---

themes/5941aefd-67b0-453d-9b62-9071a31cbb0d/chrome.css
themes/5941aefd-67b0-453d-9b62-9071a31cbb0d/theme.json

Fixes tab bar overlapping clickable elements 
Closes n7itro/Zen-Themes#8

Fix Theme: Smaller Compact Mode

---

themes/d8a9b9a4-30b7-48b5-99ad-448efa604f7e/chrome.css
themes/d8a9b9a4-30b7-48b5-99ad-448efa604f7e/preferences.json
themes/d8a9b9a4-30b7-48b5-99ad-448efa604f7e/readme.md

gave more trigger margin for top bar and added preference to remove top margin bar

Update "Only top bar in compact" theme

---

themes/67b12475-1c26-4d13-9156-297383ed8dbf/chrome.css
themes/67b12475-1c26-4d13-9156-297383ed8dbf/preferences.json
themes/67b12475-1c26-4d13-9156-297383ed8dbf/readme.md
themes/67b12475-1c26-4d13-9156-297383ed8dbf/theme.json

Changes: 
- Added bookmark bar support;
- Added option for compact toolbar;
- Added option for increased spacing; and
- Added option for merging bookmark bar with toolbar.

Update theme: Floating toolbar

---

themes/af7ee14f-e9d4-4806-8438-c59b02b77715/chrome.css
themes/af7ee14f-e9d4-4806-8438-c59b02b77715/preferences.json
themes/af7ee14f-e9d4-4806-8438-c59b02b77715/readme.md
themes/af7ee14f-e9d4-4806-8438-c59b02b77715/theme.json

- Implemented new Preferences System (with dropdowns etc.)
- Added option for custom user Gradients
- Added option for Film Grain Effect (3 Levels of Intensity)
- Added multiple (5) Levels of Gradient Intensity (Brightness)
- Adjusted values for lightness a little bit
- Fixed accent colors not applying everywhere where they should
- Fixed https://github.com/JLBlk/Zen-Themes/issues/14
- Fixed https://github.com/JLBlk/Zen-Themes/issues/12
- Fixed https://github.com/JLBlk/Zen-Themes/issues/15
- Increased Version to 1.1.0

Update Theme: SuperGradient

---

themes/753c7518-237d-480a-abfd-1f42a7eabacc/chrome.css
themes/753c7518-237d-480a-abfd-1f42a7eabacc/theme.json

For v1.0.1-a3 and above compatibility

Update theme: Zen Paper Cut Theme 1.0.1

---

themes/5941aefd-67b0-453d-9b62-9071a31cbb0d/chrome.css

Fixes centering (Closes n7itro/Zen-Themes#13) - sidebar auto-centers now :P

[fix] Smaller Compact Sidebar

---

themes/4ce2b68c-84f1-4296-b145-4e590ad7a19e/chrome.css
themes/4ce2b68c-84f1-4296-b145-4e590ad7a19e/preferences.json
themes/4ce2b68c-84f1-4296-b145-4e590ad7a19e/readme.md
themes/4ce2b68c-84f1-4296-b145-4e590ad7a19e/theme.json

Fix floating find bar issue when using narrow viewport.

Update Theme: Floating find bar

---

themes/d2953516-d239-4ef8-aac5-b238e3dc0360/readme.md

updated readme https://github.com/zen-browser/theme-store/issues/494

issue https://github.com/zen-browser/theme-store/issues/494

---

themes/2e3369c7-e450-46ba-8794-75ccb0de5e48/chrome.css
themes/2e3369c7-e450-46ba-8794-75ccb0de5e48/readme.md
themes/2e3369c7-e450-46ba-8794-75ccb0de5e48/theme.json

Fixed issue with YT video opened in new tab and the indicator shows up, hence the video is not playing.

Update theme: Now playing indicator

---

.github/workflows/update-theme-date.yml

- Updated the CHANGED_THEMES environment variable to use a space-separated list, ensuring compatibility with for loop iteration.
- Fixed an issue where theme updates would fail to process correctly due to newline-separated entries in CHANGED_THEMES.
- This change enables the action to iterate through each modified theme file accurately, improving consistency and reliability in theme timestamp updates.
This update should ensure seamless theme timestamp updates whenever changes are detected within the themes/ subdirectory.

fix: Refine `Update Theme Timestamps` Action to Correctly Parse Changed Themes

---

.github/workflows/update-theme-date.yml
scripts/rebuild_themes.py
scripts/submit_theme.py
scripts/update_theme_date.py
themes/39907934-59e9-4e42-89f0-a254d3c5e280/theme.json
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/theme.json
themes/bc25808c-a012-4c0d-ad9a-aa86be616019/theme.json

Added the --rebase flag to `Update Theme Timestamps` action in an attempt to get rid of all failure points for the action, as it ideally needs to succeed in running every time.
Added indent to `update_theme_date.py`, `rebuild_themes.py`, and `submit_theme.py` to allow for proper json formatting and easier reading of json files

Added rebase flag to `Update Theme Timestamps` action

---

themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/chrome.css
themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/theme.json

Closes https://github.com/n7itro/Zen-Themes/issues/17
Change suggested by @damian-ds7

[fix] bookmark toolbar margin

---

themes/c6813222-6571-4ba6-8faf-58f3343324f6/chrome.css
themes/c6813222-6571-4ba6-8faf-58f3343324f6/theme.json

Update Theme: Disable Rounded Corners https://github.com/zen-browser/theme-store/pull/54

Update Theme: Disable Rounded Corners

---

themes/abc2d6d8-ea9c-4313-a99c-fb1e76e8b3e5/chrome.css
themes/abc2d6d8-ea9c-4313-a99c-fb1e76e8b3e5/theme.json

- Adjusted the highlight border to show up on splitting tabs which it wasn't highlighted
(Conflicts solved)
- Solved the glitchy pixel in the corners for the panel
Before:
After:

Update Theme: Drop Shadow

---

themes/180d9426-a020-4bd7-98ec-63f957291119/chrome.css
themes/180d9426-a020-4bd7-98ec-63f957291119/theme.json

Note: I am not the original creator of this mod, I'm just proposing a simple fix for a little issue (https://github.com/zen-browser/theme-store/issues/434)
- Makes the tweaks also apply to the shrink window button (fixes #434)

Update Theme: TitleBarButton UI Tweaks

---

themes.json
themes/d2953516-d239-4ef8-aac5-b238e3dc0360/chrome.css
themes/d2953516-d239-4ef8-aac5-b238e3dc0360/preferences.json
themes/d2953516-d239-4ef8-aac5-b238e3dc0360/readme.md
themes/d2953516-d239-4ef8-aac5-b238e3dc0360/theme.json

I fixed the theme for the latest update and added some preferences, I hope they work. I couldn't find a way to test them with the browser.

Updated PywalZen for 1.0.1-a.14 + Preferences

---

themes/753c7518-237d-480a-abfd-1f42a7eabacc/chrome.css
themes/753c7518-237d-480a-abfd-1f42a7eabacc/readme.md
themes/753c7518-237d-480a-abfd-1f42a7eabacc/theme.json

Update theme: Zen paper cut theme

---

themes/bfcc400a-4ecb-4752-bfd2-a68f116a2722/readme.md

Fixes formatting and grammar errors in readme.md

Update Theme: No Gaps

---

themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/chrome.css
themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/theme.json

Closes n7itro/Zen-Themes/issues/19

[fix] bookmark toolbar tweaks

---

themes/5c4d7772-d963-4672-ab03-e9d541438881/chrome.css
themes/5c4d7772-d963-4672-ab03-e9d541438881/theme.json

fixed the ugly round border around the mute button and fixed the alignment

border and alignment fix

---

themes/c6813222-6571-4ba6-8faf-58f3343324f6/chrome.css
themes/c6813222-6571-4ba6-8faf-58f3343324f6/theme.json

Update theme: Disable Rounded Corners V3

---

themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/chrome.css
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/preferences.json
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/readme.md
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/theme.json

- Adds https://github.com/JLBlk/Zen-Themes/issues/47
- Fixes x not showing on tabs (https://github.com/JLBlk/Zen-Themes/issues/48)
- Correct Indenting
- Increased Version to 1.4.1

Update Theme: SuperPins

---

themes/f50841b2-5e4a-4534-985d-b7f7b96088c2/chrome.css
themes/f50841b2-5e4a-4534-985d-b7f7b96088c2/theme.json

the theme was broken just added a fix to work as intended

Update theme: Nohighlightsplit

---

themes/a5f6a231-e3c8-4ce8-8a8e-3e93efd6adec/chrome.css
themes/a5f6a231-e3c8-4ce8-8a8e-3e93efd6adec/preferences.json
themes/a5f6a231-e3c8-4ce8-8a8e-3e93efd6adec/readme.md
themes/a5f6a231-e3c8-4ce8-8a8e-3e93efd6adec/theme.json

- Disable transparency as an option
- Icon alignment fixed

Update Theme: Zen Cleaned URL Bar

---

themes/c8f20381-388a-4b67-b640-eaa539355ea4/chrome.css
themes/c8f20381-388a-4b67-b640-eaa539355ea4/theme.json

Update theme: Right On Hover Sidebar

---

themes/4ab93b88-151c-451b-a1b7-a1e0e28fa7f8/chrome.css
themes/4ab93b88-151c-451b-a1b7-a1e0e28fa7f8/theme.json
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/theme.json

- Removes Pinned tabs scrollbar.
- Version increase to 1.0.3

Update Theme: No Sidebar Scrollbar

---

themes.json
themes/d2953516-d239-4ef8-aac5-b238e3dc0360/chrome.css
themes/d2953516-d239-4ef8-aac5-b238e3dc0360/theme.json

Hi, some people pointed out some non-themed parts of the UI, so I fixed it.

Updated PywalZen: Fixed non-themed UI

---

themes/cfa711cf-e9f7-4c35-8289-3e7633f93565/chrome.css
themes/cfa711cf-e9f7-4c35-8289-3e7633f93565/preferences.json
themes/cfa711cf-e9f7-4c35-8289-3e7633f93565/theme.json

-> changed the dependency of reload button
-> changed the names in pref

Update Theme: Fluid url

---

themes/ae7868dc-1fa1-469e-8b89-a5edf7ab1f24/chrome.css

Added a better fade out animation

Update Theme: Load Bar

---

themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/chrome.css
themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/preferences.json
themes/ea1a5ace-f698-4b45-ab88-6e8bd3a563f0/theme.json

This give the ability to set direction of the bookmarks toolbar right-to-left right-to-left and vice versa. 
Why this approach? as someone who prefers using "Arabic" as it my native language, some settings and mods haven't been made with right-left in mind some may breaks UI and some may works incorrectly besides the fact that some translated words seems incorrect and some options aren't translated, So with this change it's possible to use the app in English but having the bookmarks started from right-to-left similar to Arabic UI
I think this is better then making new mod for this purpose 😅

Update Theme: add direction option to bookmark toolbar tweaks

---

themes/d7076c31-f6c1-4f28-b2e8-15b95f5a3d6f/chrome.css
themes/d7076c31-f6c1-4f28-b2e8-15b95f5a3d6f/readme.md
themes/d7076c31-f6c1-4f28-b2e8-15b95f5a3d6f/theme.json

Reveal search shortcut icons when focused.

Update theme: No Search Shortcut Icons

---

themes/bd92a9a0-1c00-4187-a66e-94c389fa5a59/chrome.css
themes/bd92a9a0-1c00-4187-a66e-94c389fa5a59/theme.json

- Fix window buttons on macOS extending over the edge of the window

Update Sidebar Expand on Hover to 1.1.2

---

themes/5941aefd-67b0-453d-9b62-9071a31cbb0d/chrome.css
themes/5941aefd-67b0-453d-9b62-9071a31cbb0d/theme.json

Closes https://github.com/n7itro/Zen-Themes/issues/31

[bugfix] Update Smaller Compact Mode Mod

---

themes/22c9ec3b-7c62-46ae-991f-c8fff5046829/chrome.css

- fixed invisible close button hiding title

Update Theme: Tab Numbers

---

themes/bd92a9a0-1c00-4187-a66e-94c389fa5a59/chrome.css
themes/bd92a9a0-1c00-4187-a66e-94c389fa5a59/theme.json

- Revert the refactor changes that broke the mod
- Fix the window button bug on Linux as well
- Fix compact mode detection

Update Sidebar Expand on Hover to 1.1.4

---

themes/a6335949-4465-4b71-926c-4a52d34bc9c0/theme.json

There was a missing reference for the preferences file of the Better Find Bar mod.

Update Theme: fixed missing reference to preferences.json file

---

themes/a6335949-4465-4b71-926c-4a52d34bc9c0/preferences.json
themes/a6335949-4465-4b71-926c-4a52d34bc9c0/theme.json

The preferences.json labels has been changed

Update Theme: updated preferences.json of Better Find Bar

---

themes/87196c08-8ca1-4848-b13b-7ea41ee830e7/chrome.css
themes/87196c08-8ca1-4848-b13b-7ea41ee830e7/preferences.json
themes/87196c08-8ca1-4848-b13b-7ea41ee830e7/theme.json

Update Mod to match the newest Zen version, also adds slight customization.

Update: Tab Preview Enhanced

---

themes/642854b5-88b4-4c40-b256-e035532109df/chrome.css
themes/642854b5-88b4-4c40-b256-e035532109df/preferences.json
themes/642854b5-88b4-4c40-b256-e035532109df/theme.json

This pull request includes updates to the Transparent Zen theme to enhance customization options. The most significant changes involve adding support for custom background images and improving the transparency settings.
Enhancements to customization options:
* [`themes/642854b5-88b4-4c40-b256-e035532109df/chrome.css`](diffhunk://#diff-16259534df2f321c4a0c33d4c1646efa393521dc1a5728983bc9a81475f998e1L1-R16): Added support for custom background images with CSS media queries and updated the transparency color variable.
* [`themes/642854b5-88b4-4c40-b256-e035532109df/preferences.json`](diffhunk://#diff-d07e7f9505a2acc4091a1590e95b423abe71daf82fad4ebf04bbe472f16012dfL3-R27): Updated the preferences to include options for enabling custom background images, setting the background color, and …

[Update] Transparent Zen : Added custom bg image and color options

---

themes/a5f6a231-e3c8-4ce8-8a8e-3e93efd6adec/chrome.css
themes/a5f6a231-e3c8-4ce8-8a8e-3e93efd6adec/theme.json

Rewrote the cleaned urlbar, not much should change

Update theme: Zen cleaned urlbar

---

themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/chrome.css
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/theme.json

- fixed clipping of Pins when using grid view
- increased version to 1.4.5

Update Mod: SuperPins Compatibitly Update with Zen 1.9b

---

themes/c5f7fb68-cc75-4df0-8b02-dc9ee13aa773/chrome.css

Update Audio TabIcon Plus theme for 1.7.6b

---

themes/8039de3b-72e1-41ea-83b3-5077cf0f98d1/chrome.css
themes/8039de3b-72e1-41ea-83b3-5077cf0f98d1/preferences.json
themes/8039de3b-72e1-41ea-83b3-5077cf0f98d1/theme.json

updated the theme to be able to customize the scale and the animations cubic-bezier curve

Update theme: trackpad animation

---

themes/a6335949-4465-4b71-926c-4a52d34bc9c0/chrome.css
themes/a6335949-4465-4b71-926c-4a52d34bc9c0/preferences.json
themes/a6335949-4465-4b71-926c-4a52d34bc9c0/readme.md
themes/a6335949-4465-4b71-926c-4a52d34bc9c0/theme.json

Changelog:
- Upgraded to version 1.2.0.
- Added vertical placement options (thanks to @rstanuwijaya!).
- Moved vertical position to the bottom by default.

Updated theme a6335949-4465-4b71-926c-4a52d34bc9c0 (better-findbar)

---

themes.json
themes/ae7868dc-1fa1-469e-8b89-a5edf7ab1f24/chrome.css

UI Revamp
- Follows workspace primary colour
- Works on glance
- Better design implementation

Update Theme : Load Bar

---

themes/e51b85e6-cef5-45d4-9fff-6986637974e1/chrome.css
themes/e51b85e6-cef5-45d4-9fff-6986637974e1/preferences.json

add preferences and change default opacity to 30%

mod update: smaller zen toast popup v1.1.0

---

themes/599a1599-e6ab-4749-ab22-de533860de2c/chrome.css

Contains consistent styling for "minimize" icon

Update: Pimp your PiP

---

themes/4c2bec61-7f6c-4e5c-bdc6-c9ad1aba1827/chrome.css
themes/4c2bec61-7f6c-4e5c-bdc6-c9ad1aba1827/theme.json

*  move group indicator to the left

update: Vertical Split Tab Groups

---

themes/e51b85e6-cef5-45d4-9fff-6986637974e1/chrome.css
themes/e51b85e6-cef5-45d4-9fff-6986637974e1/theme.json

initial opacity and hover bug fix with cleaner code

hot fix: mod update: smaller zen toast popup

---

themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/chrome.css

This pr is a quick attempt to get superpins working on the latest version again.

Update Mod: Fix SuperPins for latest version.

---

themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/chrome.css
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/preferences.json
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/theme.json

I haven't been maintaining SuperPins for a while cause of my several other commitments and projects, but I finally merged some pull requests that some people made (thanks to @gabry-ts and @Slddev) and this pr fixes alignment issues with icons as well as essentials padding issues.
EDIT: I have also set the defaultValue of the show-workspace-indicator property to true.
EDIT2: I have fixed the height of pinned tabs as well.
EDIT3: I have now just fixed the bottom essentials padding.
EDIT4: I have fixed the overlapping of Bottom Essentials and normal tabs.
EDIT5: I have now fixed the weird alignment of icons when the separator is not shown, as well as add back functionality for having the workspace indicator at the top and bottom, and centering the text.

Update theme: Fix majority of SuperPins.

---

themes/9bbaab67-a2c8-4d79-837f-90cd72a8932a/chrome.css
themes/9bbaab67-a2c8-4d79-837f-90cd72a8932a/theme.json

Update Theme: Big Essentials

---

themes/642854b5-88b4-4c40-b256-e035532109df/chrome.css
themes/642854b5-88b4-4c40-b256-e035532109df/preferences.json
themes/642854b5-88b4-4c40-b256-e035532109df/readme.md
themes/642854b5-88b4-4c40-b256-e035532109df/theme.json

This pull request introduces significant updates to the Zen Browser theme, including enhancements to sidebar customization, transparency settings, and preferences. It also includes minor updates to documentation and metadata. Below is a summary of the most important changes grouped by theme.
This pull request introduces several enhancements and updates to the Zen Browser theme, focusing on animation customization, sidebar transparency, and user preferences. The most significant changes include adding new animation smoothness options, implementing compact sidebar styles, and improving preference configuration.
* Added multiple animation smoothness levels (`Quick Snap`, `Smooth Flow`, `Diabolical`, `Springy`) to allow users to customize transition effects (`chrome.css`, `preferences.json`). …

Update theme : Transparent Zen - compact sidebar workaround

---

themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/chrome.css
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/preferences.json
themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/theme.json

Sorry, my bad, I forgot to update the ```preferences.json```.

Update theme: SuperPins.

---

themes/253a3a74-0cc4-47b7-8b82-996a64f030d5/chrome.css
themes/253a3a74-0cc4-47b7-8b82-996a64f030d5/preferences.json
themes/253a3a74-0cc4-47b7-8b82-996a64f030d5/theme.json

Summary:
- Fixed history side panel not closing after opening or on mod install (Potentially)

Update: Floating History

---

themes/7d577b21-4685-4db2-bb17-d39d08eec199/chrome.css
themes/7d577b21-4685-4db2-bb17-d39d08eec199/readme.md
themes/7d577b21-4685-4db2-bb17-d39d08eec199/theme.json

Please see changelog for details. This mod is maintained over at https://github.com/rsiebertdev/zen-themes.
Many thanks.

Update Theme: `bleeding-corners-fix` to `1.0.5`

---

themes/a6335949-4465-4b71-926c-4a52d34bc9c0/chrome.css
themes/a6335949-4465-4b71-926c-4a52d34bc9c0/theme.json

- Replaced `&[hidden="true"]` with `&[hidden]` for compatibility with Firefox 142 and 143.

Update Theme: better-findbar
